"""Analytic per-grating dispersion model for NIRSpec MSA shutters.

PRISM/CLEAR uses a *per-shutter* lookup table derived from
spacetelescope/msaviz's numerical integration of the pipeline
dispersion polynomials. The table lives in `data/prism_cutoffs.npz`
and is regenerated by `scripts/precompute_prism_wavelengths.py`.
Other dispersers still use the linear V2-shift approximation —
verifying them against msaviz/pipeline tables is a follow-up.
"""

from pathlib import Path

import numpy as np

from .coords import MSA_V2_REF

# Per-grating fiducial wavelength ranges (microns), sourced from JDox
# (jwst-docs.stsci.edu -> NIRSpec -> Dispersers and Filters).
GRATING_RANGES: dict[str, dict[str, tuple[float, float]]] = {
    "PRISM": {"CLEAR": (0.60, 5.30)},
    "G140M": {"F070LP": (0.70, 1.27), "F100LP": (0.97, 1.84)},
    "G235M": {"F170LP": (1.66, 3.07)},
    "G395M": {"F290LP": (2.87, 5.14)},
    "G140H": {"F070LP": (0.81, 1.27), "F100LP": (0.97, 1.84)},
    "G235H": {"F170LP": (1.66, 3.07)},
    "G395H": {"F290LP": (2.87, 5.14)},
}

# Filter blue cutoffs (microns) — hard lower bounds.
FILTER_BLUE_CUTOFF: dict[str, float] = {
    "CLEAR": 0.60,
    "F070LP": 0.70,
    "F100LP": 0.97,
    "F170LP": 1.66,
    "F290LP": 2.87,
}

# Projected MSA-to-detector dispersion span along V2 (arcsec). Placeholder per PLAN.md.
V2_DISP_EXTENT: float = 180.0

LAMBDA_PER_ARCSEC: float = (5.30 - 0.60) / V2_DISP_EXTENT  # ~0.026 μm/arcsec


# Half-width of the on-detector spectrum, in V2 arcsec, per disperser.
#
# Source: eMPT (Bonaventura et al. 2023, A&A 672, A40),
# `reference_files/prism_sep.dat`, which tabulates per-shutter +/- column
# separations for the PRISM spectrum. At a central shutter the values are
# sep_p ≈ +176, sep_m ≈ -177 columns. Each MSA column is ~0.20" along V2,
# so the projected V2 half-extent of PRISM's spectrum is ~0.20 × 176 ≈ 35".
# Within ~10 % across the MSA.
#
# For the grating modes, eMPT applies no column cutoff at all — any pair
# of shutters at the same detector-y row collide (the spectrum spans the
# entire detector). For an H-grating the spectrum reaches beyond the MSA
# in V2, so cross-quadrant pairs collide as well. We approximate both
# behaviours with a single (large) V2 half-extent below.
#
# IMPORTANT — what the visualisation actually shows. We compute the
# orange spectral-conflict shutters as "same q AND same s in the MSA grid,
# within `v2_overlap_distance` of the open shutter in V2." So:
#
#   - PRISM at a center shutter (d ~ 200): ~94 % of the row in the same
#     quadrant. (Yes, "most of the row" — physical: PRISM spectrum on
#     detector is ~70" wide in V2, the row is 73" wide.)
#   - PRISM at an edge shutter (d ~ 10): only ~51 % of the row. (The
#     spectrum runs off the end.)
#   - M / H gratings: ~100 % of the row in same quadrant.
#
# Not yet modelled: cross-quadrant collisions for grating modes. Two
# shutters in different quadrants but at the same detector y can collide;
# we'd need the eMPT shval tables to do this exactly. Reasonable
# enhancement for a future release.
SPECTRUM_V2_HALFEXTENT: dict[str, float] = {
    "PRISM": 35.0,
    "G140M": 200.0,
    "G235M": 200.0,
    "G395M": 200.0,
    "G140H": 500.0,
    "G235H": 500.0,
    "G395H": 500.0,
}


def v2_overlap_distance(disperser: str, filt: str) -> float:
    """V2 half-extent (arcsec) of the spectrum on the detector. Two same-row
    shutters whose V2 separation is less than this value collide on the
    detector. See module-level comment for the eMPT reference."""
    return SPECTRUM_V2_HALFEXTENT.get(disperser.upper(), 180.0)

# Fallback fractional gap parameters used when neither the per-
# shutter PRISM table NOR a per-disperser fiducial value is
# available. Width tightened from the previous 10 % so the gratings
# show a more believably narrow detector gap.
GAP_CENTER_REL: float = 0.50
GAP_WIDTH_REL: float = 0.04

# Per-disperser fiducial gap fallback (used only when the per-shutter
# PRISM table can't be located — kept as a safety net so vMPT still
# loads if `data/prism_cutoffs.npz` goes missing).
DETECTOR_GAP_FIDUCIAL: dict[str, tuple[float, float]] = {
    "PRISM": (1.87, 3.93),
}

# Per-shutter PRISM/CLEAR detector wavelength bounds, generated by
# `scripts/precompute_prism_wavelengths.py` and shipped at
# `data/prism_cutoffs.npz`. Loaded lazily on first lookup so import
# stays cheap. The file holds four (4, 171, 365) float32 arrays
# indexed `[q-1, s-1, d-1]`; values are NaN where the shutter's
# spectrum doesn't reach the corresponding detector.
_PRISM_TABLE_PATH = (
    Path(__file__).resolve().parent.parent / "data" / "prism_cutoffs.npz"
)
_PRISM_TABLE: dict | None = None
_PRISM_TABLE_LOAD_ATTEMPTED: bool = False


def _load_prism_table() -> dict | None:
    """Lazy-load the per-shutter PRISM bounds table. Returns None if
    the file isn't present (e.g. fresh checkout that hasn't run the
    precompute yet) — callers fall back to the fiducial values."""
    global _PRISM_TABLE, _PRISM_TABLE_LOAD_ATTEMPTED
    if _PRISM_TABLE_LOAD_ATTEMPTED:
        return _PRISM_TABLE
    _PRISM_TABLE_LOAD_ATTEMPTED = True
    if not _PRISM_TABLE_PATH.exists():
        return None
    try:
        with np.load(_PRISM_TABLE_PATH) as data:
            _PRISM_TABLE = {
                "blue_edge": data["blue_edge"],
                "gap_lo": data["gap_lo"],
                "gap_hi": data["gap_hi"],
                "red_edge": data["red_edge"],
            }
    except (OSError, KeyError, ValueError):
        _PRISM_TABLE = None
    return _PRISM_TABLE


def _prism_lookup(q: int, s: int, d: int) -> tuple[float, float, float, float] | None:
    """Read the precomputed PRISM/CLEAR wavelength bounds for shutter
    (q, s, d) where q ∈ {1..4}, s ∈ {1..171}, d ∈ {1..365}. Returns
    None if the table can't be loaded or the shutter is out of range.
    Per-value NaN means the spectrum doesn't reach that detector."""
    tbl = _load_prism_table()
    if tbl is None:
        return None
    qi, si, di = q - 1, s - 1, d - 1
    if not (0 <= qi < 4 and 0 <= si < 171 and 0 <= di < 365):
        return None
    return (
        float(tbl["blue_edge"][qi, si, di]),
        float(tbl["gap_lo"][qi, si, di]),
        float(tbl["gap_hi"][qi, si, di]),
        float(tbl["red_edge"][qi, si, di]),
    )


def cutoffs(
    v2_arcsec: float,
    v3_arcsec: float,
    disperser: str,
    filt: str,
    *,
    q: int | None = None,
    s: int | None = None,
    d: int | None = None,
) -> dict:
    """Wavelength endpoints of the dispersed spectrum on the detector
    for a shutter at (V2, V3). All values are CLAMPED to the
    disperser's intrinsic [lam_min, lam_max] range.

    If `q, s, d` are supplied AND the disperser is PRISM AND the
    precomputed table is available, returns per-shutter values from
    `data/prism_cutoffs.npz` (msaviz-derived). This is the accurate
    path — the gap location moves substantially between shutters for
    PRISM because the dispersion is highly non-linear.

    Without shutter indices (or for gratings) the function falls back
    to a linear V2-shift model: lam_blue/lam_red shift linearly with
    V2 offset from the fiducial, and the gap is held at a fiducial
    value (PRISM) or computed as a fixed fraction of the span
    (gratings).
    """
    disperser = disperser.upper()
    filt = filt.upper()
    if disperser not in GRATING_RANGES or filt not in GRATING_RANGES[disperser]:
        raise ValueError(f"Unsupported (disperser, filter) = ({disperser}, {filt})")

    lam_min, lam_max = GRATING_RANGES[disperser][filt]
    blue_cut = FILTER_BLUE_CUTOFF.get(filt, 0.0)

    def _maybe(lam, is_blue_edge: bool = False, lam_red_ref: float | None = None):
        """Apply filter blue-cut and convert NaN/None → None."""
        if lam is None:
            return None
        if isinstance(lam, float) and (lam != lam):  # NaN check w/o numpy
            return None
        if lam < blue_cut:
            if is_blue_edge and lam_red_ref is not None and lam_red_ref > blue_cut:
                return float(blue_cut)
            return None
        return float(lam)

    # Per-shutter PRISM path — preferred when indices + table are available.
    if disperser == "PRISM" and q is not None and s is not None and d is not None:
        hit = _prism_lookup(int(q), int(s), int(d))
        if hit is not None:
            blue, glo, ghi, red = hit
            # `red` should always be finite for an in-footprint shutter;
            # if both are NaN the shutter has no PRISM spectrum at all.
            if blue != blue and red != red:
                return {"lam_blue": None, "lam_gap_lo": None,
                        "lam_gap_hi": None, "lam_red": None}
            return {
                "lam_blue": _maybe(blue, is_blue_edge=True, lam_red_ref=red),
                "lam_gap_lo": _maybe(glo),
                "lam_gap_hi": _maybe(ghi),
                "lam_red": _maybe(red),
            }
        # Fall through to fiducial path if the lookup missed.

    # Fallback / grating path: linear V2 shift, fiducial or fractional gap.
    span = lam_max - lam_min
    dlam_dv2 = span / V2_DISP_EXTENT
    shift = (v2_arcsec - MSA_V2_REF) * dlam_dv2
    if disperser == "PRISM":
        # PRISM dispersion isn't linear in V2; without the table we
        # hold endpoints at the disperser's full range (per msaviz
        # the spread across shutters is ~0.01 μm anyway).
        lam_blue_raw = lam_min
        lam_red_raw = lam_max
    else:
        lam_blue_raw = lam_min + shift
        lam_red_raw = lam_max + shift
    lam_blue = max(lam_min, min(lam_max, lam_blue_raw))
    lam_red = max(lam_min, min(lam_max, lam_red_raw))

    fixed_gap = DETECTOR_GAP_FIDUCIAL.get(disperser)
    if fixed_gap is not None:
        lam_gap_lo_raw, lam_gap_hi_raw = fixed_gap
    else:
        gap_half = 0.5 * GAP_WIDTH_REL * span
        lam_gap_center_raw = lam_min + GAP_CENTER_REL * span + shift
        lam_gap_lo_raw = lam_gap_center_raw - gap_half
        lam_gap_hi_raw = lam_gap_center_raw + gap_half

    if lam_gap_hi_raw < lam_blue or lam_gap_lo_raw > lam_red:
        lam_gap_lo = None
        lam_gap_hi = None
    else:
        lam_gap_lo = max(lam_blue, min(lam_red, lam_gap_lo_raw))
        lam_gap_hi = max(lam_blue, min(lam_red, lam_gap_hi_raw))

    return {
        "lam_blue": _maybe(lam_blue, is_blue_edge=True, lam_red_ref=lam_red),
        "lam_gap_lo": _maybe(lam_gap_lo),
        "lam_gap_hi": _maybe(lam_gap_hi),
        "lam_red": _maybe(lam_red),
    }
